name: Test Page Content

on:
  workflow_run:
    workflows: ["Deploy to Production"]
    types:
      - completed

jobs:
  test-live-site:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout repo
        uses: actions/checkout@v2


      - id: live-page-test
        name: test site in production
        uses: cypress-io/github-action@v4
        with:
          spec: ${{ github.workspace }}/cypress/e2e/page_content.cy.js
          browser: chrome